name: Install clang

on:
  push:
    branches:
      - master

jobs:
  install_clang:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"

    - name: Download and install Clang
      run: |
        $downloadUrl = "https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.0/LLVM-16.0.0-win64.exe"
        $downloadPath = "$env:TEMP\LLVM-16.0.0-win64.exe"
        $installPath = ".\"

        # Download Clang
        Invoke-WebRequest -Uri $downloadUrl -OutFile $downloadPath

        # Run the downloaded installer
        Start-Process -Wait -FilePath $downloadPath

        # Move clang installation to current directory
        Move-Item -Path "$installPath\clang" -Destination $PWD -Force

        # Clean up the downloaded installer
        Remove-Item -Path $downloadPath -Force

    - name: Commit and push binaries
      run: |
        git checkout -b clang
        git add .
        git commit -m "Add Clang install"
        git push origin clang --force
