name: Install clang

on:
  push:
    branches:
      - master

jobs:
  install_clang:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"

    - name: Download and install Clang
      run: |
        $downloadUrl = "https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.0/LLVM-16.0.0-win64.exe"
        $downloadPath = "$env:TEMP\LLVM-16.0.0-win64.exe"
        $installPath = "$PWD\clang"

        Write-Host "Downloading Clang installer..."
        Invoke-WebRequest -Uri $downloadUrl -OutFile $downloadPath

        Write-Host "Running Clang installer silently..."
        Start-Process -Wait -FilePath $downloadPath -ArgumentList "/S", "/D=$installPath"

        Write-Host "Cleaning up downloaded installer..."
        Remove-Item -Path $downloadPath -Force

    - name: Commit and push binaries
      run: |
        git checkout -b clang
        git add .
        git commit -m "Add Clang install"
        git push origin clang --force
