name: Create Clang Release

on:
  push:
    branches:
      - masters

jobs:
  create_release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"

    - name: Download and install Clang
      run: |
        $downloadUrl = "https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.0/LLVM-16.0.0-win64.exe"
        $downloadPath = "$env:TEMP\LLVM-16.0.0-win64.exe"
        $installPath = "$PWD\clang"

        Write-Host "Downloading Clang installer..."
        Invoke-WebRequest -Uri $downloadUrl -OutFile $downloadPath

        Write-Host "Running Clang installer silently..."
        Start-Process -Wait -FilePath $downloadPath -ArgumentList "/S", "/D=$installPath"

        Write-Host "Cleaning up downloaded installer..."
        Remove-Item -Path $downloadPath -Force

    - name: Compress Clang installation
      run: |
        Compress-Archive -Path "clang" -DestinationPath "clang.zip"

    - name: Get current date and time
      id: datetime
      run: echo "::set-output name=date::$(Get-Date -Format 'yyyyMMdd-HHmmss')"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.datetime.outputs.date }}
        release_name: Clang Release ${{ steps.datetime.outputs.date }}
        draft: false
        prerelease: false

    - name: Upload Clang ZIP to Release
      id: upload_clang
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: clang.zip
        asset_name: clang.zip
        asset_content_type: application/zip
