name: Build and Install Clang

on:
  push:
    branches:
      - master

jobs:
  build_clang:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Visual Studio 2019 image
      uses: actions/setup-msbuild@v1
      with:
        vs-version: '2019'

    - name: Build Clang
      run: |
        git clone --depth 1 https://github.com/llvm/llvm-project.git
        mkdir build
        cd build
        cmake -G "Visual Studio 16 2019" -A x64 -Thost=x64 -DLLVM_ENABLE_PROJECTS=clang -DCMAKE_INSTALL_PREFIX=install ../llvm-project/llvm
        cmake --build . --config Release --target install

    - name: Commit and push binaries
      run: |
        git checkout -b clang
        git add .
        git commit -m "Add Clang build"
        git push origin clang --force
