name: Build and Release FFmpeg for Windows

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List files in current directory
      run: |
        dir

    - name: Unzip FFmpeg source code
      run: |
        tar --version
        7z --version
        tar -xf ffmpeg-6.0.tar.xz
        cd ffmpeg-6.0
        dir

    - name: Build FFmpeg libraries and includes
      run: |
        cd ffmpeg-6.0
        ./configure --arch=x86 --target-os=mingw32 --cross-prefix=i686-w64-mingw32- --prefix=build --toolchain=msvc
        make
        make install

    - name: List files in build directory
      run: |
        dir ffmpeg-6.0\build

    - name: Zip FFmpeg build
      run: |
        cd ffmpeg-6.0\build
        zip -r ffmpeg-windows.zip *

    - name: List files in build directory after zip
      run: |
        dir ffmpeg-6.0\build

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: $
