name: Build and Release Pre-built FFmpeg for Windows

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download and extract FFmpeg binaries
      run: |
        mkdir ffmpeg
        cd ffmpeg
        curl -LO https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full.zip
        7z x ffmpeg-release-full.zip

    - name: Zip FFmpeg build
      run: |
        cd ffmpeg
        zip -r ffmpeg-windows.zip *

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_id }}
        release_name: Pre-built FFmpeg ${{ github.run_id }}
        draft: false
        prerelease: false

    - name: Upload FFmpeg ZIP to Release
      id: upload_ffmpeg
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ffmpeg/ffmpeg-windows.zip
        asset_name: ffmpeg-windows.zip
        asset_content_type: application/zip
