name: Decompress and Push FFmpeg Archive

on:
  push:
    branches:
      - master

jobs:
  decompress_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup FFmpeg archive
      run: |
        mkdir ffmpeg-6.0
        tar -xJf ffmpeg-6.0.tar.xz -C ffmpeg-6.0 --strip-components=1

    - name: Commit and Push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@users.noreply.github.com"
        git add ffmpeg-6.0
        git commit -m "Decompressed FFmpeg archive"
        git push origin master
