name: Build and Release FFmpeg for Windows

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up FFmpeg environment
      run: |
        sudo apt-get update
        sudo apt-get install -y curl xz-utils build-essential mingw-w64 nasm wine64

    - name: Download FFmpeg source code
      run: |
        curl -O https://ffmpeg.org/releases/ffmpeg-6.0.tar.xz
        tar -xf ffmpeg-6.0.tar.xz
        cd ffmpeg-6.0
        ls -la

    - name: Build FFmpeg libraries and includes
      run: |
        cd ffmpeg-6.0
        ./configure --arch=x86 --target-os=mingw32 --cross-prefix=i686-w64-mingw32- --prefix=build --toolchain=msvc
        make
        make install

    - name: Zip FFmpeg build
      run: |
        cd build
        zip -r ffmpeg-windows.zip *

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_id }}
        release_name: FFmpeg Build ${{ github.run_id }}
        draft: false
        prerelease: false

    - name: Upload FFmpeg ZIP to Release
      id: upload_ffmpeg
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ffmpeg-6.0/build/ffmpeg-windows.zip
        asset_name: ffmpeg-windows.zip
        asset_content_type: application/zip
