name: Build and Release FFmpeg for Windows

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # - name: Set up MSVC environment
    #   run: |
    #     choco install visualstudio2019buildtools --package-parameters "--includeRecommended --includeOptional"
    #     choco install nasm
    #     Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1

    - name: Build FFmpeg libraries and includes
      run: |
        cd ffmpeg-6.0  # Navigate to the extracted FFmpeg directory
        $env:PATH += ";C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64"
        ./configure --toolchain=msvc --arch=x86
        make
        make install

    - name: Zip FFmpeg build
      run: |
        cd ffmpeg-6.0/build
        zip -r ffmpeg-windows.zip *

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_id }}
        release_name: FFmpeg Build ${{ github.run_id }}
        draft: false
        prerelease: false

    - name: Upload FFmpeg ZIP to Release
      id: upload_ffmpeg
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ffmpeg-6.0/build/ffmpeg-windows.zip
        asset_name: ffmpeg-windows.zip
        asset_content_type: application/zip
