name: Install GCC and Create Binaries Branch

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print Possible Install Paths
        run: |
          echo "Checking possible MinGW installation paths:"
          dir C:\tools || true
          dir C:\msys64 || true
          dir C:\msys64\mingw64 || true
          dir C:\ || true

      - name: Create Binaries Branch
        run: |
          mkdir temp
          cp "C:\msys64\mingw64\*" temp/
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout --orphan binaries
          mv temp/* .
          dir
          git status
          git add .
          git status
          git commit -m "Add GCC binaries"
          git status
          git push -f origin binaries
