name: Copy GCC Binaries to Binaries Branch

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up MinGW-w64
      run: |
        sudo apt-get update
        sudo apt-get install -y mingw-w64
        
    - name: Determine GCC binary path
      run: |
        gcc_path=$(dirname "$(which x86_64-w64-mingw32-gcc)")
        echo "GCC binaries located at: $gcc_path"
        
    - name: Create binaries branch
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git checkout --orphan binaries
        git rm -rf .
        
    - name: Copy GCC binaries
      run: |
        cp -r "$gcc_path"/*-w64-mingw32/bin/{gcc,g++,gfortran} .
        git add .
        git commit -m "Add GCC binaries from MinGW-w64"
        git push --force origin binaries
