name: Download and Push MinGW-w64

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create binaries branch
      run: |
        git config user.email "action@github.com"
        git config user.name "GitHub Action"
        git checkout -b binaries

    - name: Download MinGW-w64
      run: |
        if ! test -d mingw-w64; then
          curl -LJO https://github.com/jmeubank/mingw-w64-build/releases/latest/download/mingw-w64.tar.gz
          tar -xzf mingw-w64.tar.gz
          rm mingw-w64.tar.gz
        fi

    - name: Push MinGW-w64
      run: |
        git add mingw-w64
        git commit -m "Add MinGW-w64"
        git push --force origin binaries
