name: Install GCC and Create Binaries Branch

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install GCC
        run: |
          choco install mingw -y
          set PATH="C:\tools\mingw64\bin;%PATH%"
          mingw64_path=$(cygpath -w "$(command -v gcc | sed 's|/[^/]*$||')")
          echo ::set-env name=MINGW64_PATH::${mingw64_path}

      - name: Get MinGW Installation Path
        id: mingw-path
        run: |
          echo "MINGW64_PATH=${{ env.MINGW64_PATH }}" >> $GITHUB_ENV

      - name: Create Binaries Branch
        run: |
          mkdir binaries
          cp $MINGW64_PATH/* binaries/
          git checkout --orphan binaries
          git rm -rf .
          mv binaries/* .
          git add .
          git commit -m "Add GCC binaries"
          git push -f origin binaries
