name: Install GCC and Create Binaries Branch

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install GCC
        run: |
          choco install mingw -y
          set PATH="/c/tools/mingw64/bin:$PATH"

      - name: Create Binaries Branch
        run: |
          mkdir binaries
          cp /c/tools/mingw64/bin/* binaries/
          git checkout --orphan binaries
          git rm -rf .
          mv binaries/* .
          git add .
          git commit -m "Add GCC binaries"
          git push -f origin binaries
