name: Download and Push MinGW-w64

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.email "action@github.com"
        git config user.name "GitHub Action"

    - name: Create binaries branch
      run: |
        git checkout -b binaries
        git push origin binaries

    - name: Download and extract MinGW-w64
      run: |
        mkdir mingw-w64
        cd mingw-w64
        wget https://sourceforge.net/projects/mingw-w64/files/mingw-w64/mingw-w64-release/mingw-w64-v8.0.0.tar.bz2
        tar -xjf mingw-w64-v8.0.0.tar.bz2
        cd ..

    - name: Push MinGW-w64
      run: |
        git add mingw-w64
        git commit -m "Add MinGW-w64"
        git push --force origin binaries
