name: Download and Push GCC for Windows

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download MinGW-w64 GCC
      run: |
        git config user.email "action@github.com"
        git config user.name "GitHub Action"
        
        git checkout -b binaries
        
        wget https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/rubenvb/gcc-10-branch-w64/gcc-10.2.0-branch-x86_64-win32-seh-rubenvb.7z/download -O gcc.7z
        7z x gcc.7z -ogcc
        rm gcc.7z

        git add gcc
        git commit -m "Add MinGW-w64 GCC binary"
        
        git push --force origin binaries
