name: Install MSYS2 and Push Binaries

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Download MSYS2 Installer
      run: |
        $url = 'https://github.com/msys2/msys2-installer/releases/download/2023-07-18/msys2-x86_64-20230718.exe'
        Invoke-WebRequest -Uri $url -OutFile 'msys2-installer.exe'
    
    - name: Install MSYS2
      run: |
        .\msys2-installer.exe in --confirm-command --accept-messages --root $PWD
    
    - name: Set up Git
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
    
    - name: Create Binaries Branch
      run: |
        git checkout -b binaries
        git add .
        git commit -m "Add MSYS2 installation"
        git push origin binaries --force
