name: Build GCC for Windows

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Build GCC
      run: |
        mkdir gcc-build
        cd gcc-build
        ../configure --target=x86_64-w64-mingw32 --enable-targets=all --enable-languages=c,c++
        make -j$(nproc)
        cd ..

    - name: Push binaries
      run: |
        git config user.email "action@github.com"
        git config user.name "GitHub Action"
        git checkout -b binaries
        mv gcc-build/x86_64-w64-mingw32/bin/* .
        git add .
        git commit -m "Add GCC binaries for Windows"
        git push --force origin binaries
