name: Download and Push MinGW-w64

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Git
      run: |
        git config user.email "action@github.com"
        git config user.name "GitHub Action"

    - name: Create binaries branch
      run: |
        git checkout -b binaries
        git push origin binaries

    - name: Extract MinGW-w64
      run: |
        tar -xjf mingw-w64-v8.0.0.tar.bz2 -C mingw-w64

    - name: Push MinGW-w64
      run: |
        git add mingw-w64
        git commit -m "Add MinGW-w64"
        git push origin binaries
