name: Install GCC and Create Binaries Branch

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install GCC
        run: |
          choco install mingw -y
          set PATH="C:\tools\mingw64\bin;%PATH%"

      - name: Get MinGW Installation Path
        id: mingw-path
        run: |
          echo "::set-output name=path::$(for /f %%i in ('where gcc') do @echo %%~dpi)"

      - name: Create Binaries Branch
        run: |
          mkdir binaries
          copy ${{ steps.mingw-path.outputs.path }}bin\* binaries\
          git checkout --orphan binaries
          git rm -rf .
          mv binaries/* .
          git add .
          git commit -m "Add GCC binaries"
          git push -f origin binaries
