name: Download and Push MinGW-w64

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download and extract MinGW-w64 distribution
      run: |
        wget https://github.com/mstorsjo/mingw-w64/releases/download/mingw-w64-v8.0.0/mingw-w64-x86_64-8.0.0-release-posix-seh-rt_v6-rev0.7z
        7z x mingw-w64-x86_64-8.0.0-release-posix-seh-rt_v6-rev0.7z
        cd mingw-w64-x86_64-8.0.0-release-posix-seh-rt_v6-rev0

    - name: Push MinGW-w64 Distribution
      run: |
        git config user.email "action@github.com"
        git config user.name "GitHub Action"
        git checkout -b binaries
        git add mingw-w64-x86_64-8.0.0-release-posix-seh-rt_v6-rev0
        git commit -m "Add MinGW-w64 Distribution"
        git push --force origin binaries

