name: Install GCC and Create Binaries Branch

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy binaries
        run: |
          tree /f "C:\msys64\mingw64"
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout -b binaries
          mkdir temp
          robocopy "C:\msys64\mingw64" "temp" /E
          mv temp/* .
          echo "BEFORE ADD"
          echo "ROOT"
          tree /f
          echo "BIN"
          tree /f bin
          git status
          git add -A
          echo "AFTER ADD"
          git status
          git commit -m "Add GCC binaries"
          git status
          git push -f origin binaries
