name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up GCC dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git libgmp-dev libmpfr-dev libmpc-dev

    - name: Download and build
      run: |
        git clone https://gcc.gnu.org/git/gcc.git
        cd gcc
        ./contrib/download_prerequisites
        mkdir build
        cd build
        ../configure --prefix=$(pwd)/../install --disable-multilib --enable-languages=c,c++ \
                     --target=x86_64-w64-mingw32 --with-gmp=/usr/include --with-mpfr=/usr/include --with-mpc=/usr/include
        make -j$(nproc) all-gcc
        make install-gcc
        GCC_BINARY=$(find $(pwd)/../install/bin -name "gcc" -type f)
        cp $GCC_BINARY ../../gcc.exe
        cd ../..
        rm -rf gcc

    - name: Set up Git
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"

    - name: Commit and push binaries
      run: |
        git checkout -b binaries
        git add gcc.exe
        git commit -m "Add gcc.exe binary"
        git push origin binaries --force
