name: Install MinGW Binaries

on:
  push:
    branches:
      - master

jobs:
  install_mingw:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download and unzip MinGW binaries
      run: |
        curl -L -o mingw.7z https://github.com/niXman/mingw-builds-binaries/releases/download/13.1.0-rt_v11-rev1/i686-13.1.0-release-posix-dwarf-msvcrt-rt_v11-rev1.7z
        7z x mingw.7z -o./mingw
        rm mingw.7z

    - name: Set up Git
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
    
    - name: Create binaries branch
      run: |
        git checkout -b binaries
        git add mingw
        git commit -m "Add MinGW binaries"
        git push origin binaries --force
