name: Install clang

on:
  push:
    branches:
      - master

jobs:
  install_clang:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake curl p7zip-full

    - name: Download and build clang
      run: |
        LLVM_INSTALL_PATH=~/llvm
        LLVM_VERSION=13.0.0
        NUM_THREADS=$(nproc)  # Get number of CPU cores

        # Download LLVM/Clang source code
        curl -L https://github.com/llvm/llvm-project/releases/download/llvmorg-$LLVM_VERSION/llvm-project-$LLVM_VERSION.tar.xz -o llvm.tar.xz
        7z x llvm.tar.xz
        mv llvm-project-$LLVM_VERSION llvm

        # Build LLVM/Clang
        cd llvm
        mkdir build
        cd build
        cmake -G "Unix Makefiles" -DLLVM_ENABLE_PROJECTS=clang -DCMAKE_INSTALL_PREFIX=$LLVM_INSTALL_PATH ..
        make -j$NUM_THREADS
        make install

        echo "LLVM/Clang $LLVM_VERSION has been successfully built and installed to $LLVM_INSTALL_PATH"

    - name: Set up Git
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"

    - name: Create binaries branch
      run: |
        git checkout -b binaries
        git add .
        git commit -m "Add clang binaries"
        git push origin binaries --force
