name: Install clang

on:
  push:
    branches:
      - master

jobs:
  install_clang:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake curl

    - name: Download and build clang
      run: |
        LLVM_INSTALL_PATH=~/llvm
        LLVM_VERSION=16.0.6
        NUM_THREADS=$(nproc)  # Get number of CPU cores

        # Configure and build LLVM/Clang
        mkdir llvm-build
        cd llvm-build
        cmake -DLLVM_ENABLE_PROJECTS='clang' -DCMAKE_INSTALL_PREFIX=$LLVM_INSTALL_PATH ../llvm
        cmake --build . --target install -j $NUM_THREADS

        echo "LLVM/Clang $LLVM_VERSION has been successfully built and installed to $LLVM_INSTALL_PATH"

    - name: Set up Git
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"

    - name: Create binaries branch
      run: |
        git checkout -b binaries
        git add .
        git commit -m "Add clang binaries"
        git push origin binaries --force
