name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up GCC dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git

    - name: Download and build
      run: |
        git clone https://gcc.gnu.org/git/gcc.git
        cd gcc
        ./configure --prefix=$(pwd) --disable-multilib --enable-languages=c,c++
        make -j$(nproc)
        make install
        GCC_BINARY=$(find $(pwd)/bin -name "gcc.exe" -type f)
        cp $GCC_BINARY ../gcc.exe
        cd ..
        rm -rf gcc

    - name: Set up Git
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"

    - name: Commit and push binaries
      run: |
        git checkout -b binaries
        git add gcc.exe
        git commit -m "Add gcc.exe binary"
        git push origin binaries --force
