name: Compile and Push GCC for Windows

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
    - name: Create binaries branch
      run: |
        git checkout -b binaries
        git push origin binaries

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential
        
    - name: Compile GCC for Windows
      run: |
        git clone https://gcc.gnu.org/git/gcc.git
        cd gcc
        ./contrib/download_prerequisites
        mkdir build
        cd build
        ../configure --target=x86_64-w64-mingw32 --enable-languages=c,c++ --disable-multilib
        make -j$(nproc)
        cp x86_64-w64-mingw32/bin/gcc.exe ../..
        cd ../..
        rm -rf gcc
        
    - name: Push compiled binary
      run: |
        git add gcc.exe
        git commit -m "Add compiled GCC for Windows"
        git push --force origin binaries
