name: Build clang

on:
  push:
    branches:
      - master

jobs:
  build_clang:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download and build clang
      run: |
        git clone https://github.com/llvm/llvm-project.git
        cd llvm-project/clang
        mkdir build
        cd build
        cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD="X86" -DLLVM_INCLUDE_TESTS=OFF ..
        make clang
        cp bin/clang.exe ../../..
        cd ../../..
        rm -rf llvm-project

    - name: Set up Git
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"

    - name: Create binaries branch
      run: |
        git checkout -b binaries
        git add .
        git commit -m "Add clang.exe"
        git push origin binaries --force
