name: Install and Release Make for Windows

on:
  push:
    branches:
      - masters

jobs:
  install_and_release_make:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Install Make using Chocolatey
        run: |
          choco install make -y

      - name: Get Make version
        id: make_version
        run: |
          $makeVersion = (make --version | Select-String -Pattern '\d+\.\d+\.\d+').Matches.Value
          echo "::set-output name=version::$makeVersion"

      - name: Create Make Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.make_version.outputs.version }}
          release_name: Make Release v${{ steps.make_version.outputs.version }}
          draft: false
          prerelease: false

      - name: Package Make installation
        run: |
          $makePath = "C:\ProgramData\chocolatey\lib\make\tools"
          $zipFileName = "make_v${{ steps.make_version.outputs.version }}.zip"
          Compress-Archive -Path $makePath -DestinationPath $zipFileName

      - name: Upload Make ZIP to Release
        id: upload_make
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: make_v${{ steps.make_version.outputs.version }}.zip
          asset_name: make_v${{ steps.make_version.outputs.version }}.zip
          asset_content_type: application/zip
