name: Build MinGW

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download and build MinGW
      run: |
        curl -Lo mingw-get-setup.exe https://netix.dl.sourceforge.net/project/mingw/Installer/mingw-get-setup.exe
        mingw-get-setup.exe

    - name: Move MinGW to repository root
      run: |
        mv C:\mingw64 .\mingw64
        Remove-Item mingw-get-setup.exe

    - name: Set up Git
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"

    - name: Commit and push MinGW
      run: |
        git checkout -b mingw
        git add mingw64
        git commit -m "Add MinGW"
        git push origin mingw --force
