name: Install Python 3.12.0 on Windows

on:
  push:
    branches:
      - master

jobs:
  install_and_upload:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Python installer
      run: |
        Invoke-WebRequest -Uri "https://www.python.org/ftp/python/3.12.0/python-3.12.0-amd64.exe" -OutFile python-installer.exe

    - name: Install Python
      run: |
        .\python-installer.exe /quiet InstallAllUsers=1 PrependPath=1 TargetDir=C:\Python312

    - name: Set up Git
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"

    - name: Get Python installation path
      id: get_python_path
      run: |
        Get-Command python | ForEach-Object { $_.Source.Replace("python.exe", "") }

    - name: Package Python binaries
      run: |
        $pythonPath = "${{ steps.get_python_path.outputs.stdout }}"
        Compress-Archive -Path $pythonPath -DestinationPath "python312.zip"

    - name: Get current date and time
      id: datetime
      run: echo "::set-output name=date::$(Get-Date -Format 'yyyyMMdd-HHmmss')"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.datetime.outputs.date }}
        release_name: "Python 3.12.0 Release ${{ steps.datetime.outputs.date }}"
        draft: false
        prerelease: false

    - name: Upload Python ZIP to Release
      id: upload_python
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: python312.zip
        asset_name: python312.zip
        asset_content_type: application/zip
