name: Install Python on Windows

on:
  push:
    branches:
      - master

jobs:
  install_and_upload:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"

    - name: Download Python Installer
      run: |
        $pythonUrl = "https://www.python.org/ftp/python/3.12.0/python-3.12.0-amd64.exe"
        Invoke-WebRequest -Uri $pythonUrl -OutFile python-installer.exe

    - name: Install Python
      run: |
        Start-Process -Wait -FilePath "python-installer.exe" -ArgumentList "/quiet", "/passive", "/norestart"

    - name: Get Python Version
      id: python_version
      run: |
        python --version | Out-File python_version.txt
      shell: cmd

    - name: Package Python Binaries
      run: |
        Compress-Archive -Path "C:\Program Files\Python" -DestinationPath "python.zip"
      shell: cmd

    - name: Get current date and time
      id: datetime
      run: echo "::set-output name=date::$(Get-Date -Format 'yyyyMMdd-HHmmss')"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.datetime.outputs.date }}
        release_name: Python Release ${{ steps.datetime.outputs.date }}
        draft: false
        prerelease: false

    - name: Upload Python ZIP to Release
      id: upload_python
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: python.zip
        asset_name: python.zip
        asset_content_type: application/zip
